import type { Metadata } from "next"
import { ABeeZee, Dancing_Script, Inter } from "next/font/google"
import "./globals.css"
import Header from "@/components/header"
import { AntdRegistry } from "@ant-design/nextjs-registry"
import Link from "next/link"

const inter = Inter({
  subsets: ["latin"],
  weight: "400",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
  modal,
  analytics,
  team,
}: {
  children: React.ReactNode
  modal: React.ReactNode
  analytics: React.ReactNode
  team: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          {children}
          {modal}
          {/* {analytics}
          {team} */}
        </AntdRegistry>
      </body>
    </html>
  )
}
