import type { Metadata } from "next"
import { ABeeZee, Dancing_Script, Inter } from "next/font/google"
import "./globals.css"
import Header from "@/components/header"
import { AntdRegistry } from "@ant-design/nextjs-registry"

const inter = Inter({
  subsets: ["latin"],
  weight: "400",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Header /> */}
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  )
}
